DROP TABLE if EXISTS `student`;
CREATE TABLE `student` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) DEFAULT NULL  COMMENT '姓名',
  `gender` TINYINT(4) NOT NULL  COMMENT '性别0-男;1-女',
  `birthday` DATETIME DEFAULT NULL COMMENT '生日',
  `height` INT(11) DEFAULT NULL COMMENT '身高',
  `class_id` BIGINT(20) NOT NULL COMMENT '班级',
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1000000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='学生';

DROP TABLE if EXISTS `class`;
CREATE TABLE `class` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `grade` TINYINT(4) NOT NULL  COMMENT '年级',
  `num` TINYINT(4) NOT NULL  COMMENT '班级',
  `student_count` INT NOT NULL DEFAULT 0 COMMENT '学生人数',
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1000000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='班级';

